#!/usr/bin/env groovy

library 'codeveros-library'

runNodeSvcPipeline([
  repository: 'coveros/codeveros-gateway',
  servicePath: 'services/gateway/nodejs/',
  chartPath: 'charts/codeveros-gateway/'
])
