#!/usr/bin/env groovy

library 'codeveros-library@feature/unstubbing-stages'

runNodeSvcPipeline([
  repository: 'coveros/codeveros-gateway',
  servicePath: 'services/gateway/nodejs/',
  chartPath: 'charts/codeveros-gateway/'
])
