#!/usr/bin/env groovy

library 'codeveros-library@feature/monorepo'

dir('services/user-service/nodejs') {
  runNodeSvcPipeline([
    repository: 'coveros/codeveros-user-service',
    basePath: 'services/user-service/nodejs/'
  ])
}
