#!/usr/bin/env groovy

library 'codeveros-library@feature/monorepo'

runNodeSvcPipeline([
  repository: 'coveros/codeveros-auth-service',
  servicePath: 'services/auth-service/nodejs/',
  chartPath: 'charts/codeveros-auth-service/'
])
