{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-config
  labels:
    {{- include "codeveros.labels" . | nindent 4 }}
data:
  codeveros.conf: |-
    server {
      listen 0.0.0.0:8080;

      location /api/ {
        proxy_pass {{ printf "http://%s-codeveros-gateway:8080" .Release.Name }};
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        proxy_pass {{ printf "http://%s-codeveros-ui:80" .Release.Name }};
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
{{- end }}
