{{- if not .Values.ingress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codeveros.fullname" . }}
  labels:
    {{- include "codeveros.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "codeveros.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "codeveros.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.proxy.imageRepository }}:{{ .Values.proxy.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "codeveros.fullname" . }}
{{- end }}
