{{- if not .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codeveros.fullname" . }}
  labels:
    {{- include "codeveros.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort}}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "codeveros.selectorLabels" . | nindent 4 }}
{{- end }}
