#!/usr/bin/env groovy

library 'codeveros-library'

runNodeSvcPipeline([
  repository: 'coveros/codeveros-training-service',
  servicePath: 'services/training-service/nodejs/',
  chartPath: 'charts/codeveros-training-service/'
])
