replicaCount: 1

image:
  repository: ghcr.io/coveros/codeveros-training-service
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

env:
  dbPort: "27017"
  dbDatabase: "training"

mongodb:
  # codeveros currently doesn't use authentication between the service and the database
  auth:
    enabled: false
  nameOverride: training-service-mongodb
