replicaCount: 1

image:
  repository: coveros/codeveros-auth-service
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
