{{- if .Values.ingress.enabled }}
{{ $latestVersion := .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- if $latestVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "codeveros-gateway.fullname" . }}
  labels:
  {{- include "codeveros-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            {{- if $latestVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "codeveros-gateway.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            {{- else }}
            backend:
              serviceName: {{ include "codeveros-gateway.fullname" . }}
              servicePort: {{ .Values.service.port }}
            {{- end }}
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
{{- end }}
