nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

codeveros-ui:
  ingress:
    enabled: false

codeveros-gateway:
  ingress:
    enabled: false

nginx:
  enabled: false
  service:
    type: NodePort
  existingServerBlockConfigMap: '{{ include "codeveros.fullname" . }}'
