nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hostName:

proxy:
  imageRepository: nginx
  imageTag: 1.19.0
  imagePullPolicy: IfNotPresent
  replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort:
