codeveros-ui:
  ingress:
    enabled: false

codeveros-gateway:
  ingress:
    enabled: false

nginx:
  enabled: false
  service:
    type: NodePort
  existingServerBlockConfigmap: "{{ .Release.Name }}-proxy"
