codeveros-ui:
  ingress:
    enabled: false

codeveros-gateway:
  ingress:
    enabled: false

proxy:
  enabled: true
  service:
    type: NodePort
  existingServerBlockConfigmap: "{{ .Release.Name }}-proxy-config"
