apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 250m
    max: # max and min define the limit range
      cpu: "1"
    min:
      cpu: 100m
    type: Container

# for $n in {1..15}; do kubectl apply -f limit-range.yml --namespace=namespace${n}; done
