name: Test Codeveros Auth Service - Node.js

on:
  pull_request:
    branches:
      - master
    paths:
      - services/auth-service/nodejs/**

defaults:
  run:
    working-directory: services/auth-service/nodejs

env:
  node_version: 12.x
  REGISTRY: ghcr.io
  IMAGE_NAME: coveros/codeveros-auth-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install NPM Dependencies
        run: npm ci --quiet

      - name: Lint Code
        run: npm run checkstyle:ci

      - name: Unit Test
        run: npm run test-ci

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/auth-service/nodejs
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
