name: Test Codeveros MS

on:
  push:
    branches: [ master ]
    paths:
      - libraries/codeveros-ms/**
  pull_request:
    branches: [ master ]
    paths:
      - libraries/codeveros-ms/**

defaults:
  run:
    working-directory: libraries/codeveros-ms

env:
  node_version: 14.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build Library
        run: npm run build
      - name: Lint code
        run: npm run lint
      - name: Unit Test
        run: npm test
        env:
          CI: true
