name: Test Codeveros Gateway - Node.js

on:
  pull_request:
    branches:
      - master
    paths:
      - services/gateway/nodejs/**

defaults:
  run:
    working-directory: services/gateway/nodejs

env:
  node_version: 12.x
  dockerRepository: coveros/codeveros-gateway

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: Install NPM Dependencies
        run: npm ci --quiet
      - name: Lint Code
        run: npm run checkstyle:ci
      - name: Unit Test
        run: npm run test-ci
      - name: Build Docker Image
        run: docker build . --tag ${{ env.dockerRepository }}:$(date +%s)
