name: Test Codeveros UI - Angular

defaults:
  run:
    working-directory: services/ui/angular

on:
  pull_request:
    branches:
      - master
    paths:
      - services/ui/angular/**

env:
  node_version: 12.x
  dockerRepository: coveros/codeveros-ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM Dependencies
      run: npm ci --quiet
    - name: Lint Code
      run: npm run checkstyle
    - name: Unit Test
      run: npm run test
    - name: Build UI static files
      run: npm run build.production
    - name: Build Docker Image
      run: docker build . --tag ${{ env.dockerRepository }}:$(date +%s)
